version: '3.3'
services:
  db:
    image: postgres:14.5
    volumes:
      - /var/lib/postgresql/data/
    ports:
      - "5432:5432"
    env_file:
      - src/.env

  backend:
    container_name: backend
    build:
      dockerfile: Dockerfile
#    image: atreids/foodgram_backend:latest
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - src/.env